# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('secuencia', models.CharField(max_length=20)),
                ('total', models.FloatField()),
                ('numero', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('identificacion', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturas.Usuario'),
        ),
    ]
