# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['fecha']},
        ),
        migrations.AddField(
            model_name='factura',
            name='deducible',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='factura',
            name='gasto',
            field=models.CharField(default='nada', max_length=40),
        ),
        migrations.AddField(
            model_name='factura',
            name='razon_social',
            field=models.CharField(default='nada', max_length=40),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='secuencia',
            field=models.CharField(default='nada', max_length=20),
        ),
    ]
