# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0003_auto_20170901_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='razon_social',
            field=models.CharField(max_length=40),
        ),
    ]
