# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0004_auto_20170901_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='deducible',
            field=models.FloatField(),
        ),
    ]
