# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0005_auto_20170901_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo',
            field=models.CharField(default='nada', max_length=100),
        ),
    ]
