# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0009_auto_20170901_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['fecha']},
        ),
    ]
