# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0010_auto_20170901_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo',
            field=models.CharField(default='Sin archivo', max_length=100),
        ),
    ]
