# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0011_auto_20170902_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='tipo',
            new_name='tipo_de_documento',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='gasto',
            new_name='tipo_de_gasto',
        ),
    ]
