# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturas', '0012_auto_20170902_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha']},
        ),
    ]
